export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const DELETE_FROM_FAVORITE = "DELETE_FROM_FAVORITE";
export const DELETE_FROM_BASKET = "DELETE_FROM_BASKET";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const CONVERT_CURRENCY = "CONVERT_CURRENCY";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";